chore: Disable main branch protection for direct commits and pushes

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -8,10 +8,11 @@ fi
 
 branch="$(git rev-parse --abbrev-ref HEAD)"
 
-if [ "$branch" = "main" ]; then
-  echo "You can't commit directly to main - please check out a branch."
-  exit 1
-fi
+# maximosyntax_change - disabled main branch protection for direct commits
+# if [ "$branch" = "main" ]; then
+#   echo "You can't commit directly to main - please check out a branch."
+#   exit 1
+# fi
 
 # Detect if running on Windows and use pnpm.cmd, otherwise use pnpm.
 if [ "$OS" = "Windows_NT" ]; then
